[build]
  base = "."
  command = "npm run build"
  publish = "out"
[functions]
  directory = "YOUR_BASE_DIRECTORY/api/"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-next-dynamic"